import {
  CRAWLER_CHARACTER_COVER_SRC,
  CRAWLER_PSYCHUBE_COVER_SRC,
  CRAWLER_STORY_COVER_SRC,
} from './crawlerCovers'

export const HOME_VIDEO_SRC = '/videos/pv.mp4'
export const GLOBAL_BACKGROUND_IMAGE_SRC = '/images/global-background.png'

const CHARACTER_CATEGORY_KEY = '\u4eba\u7269'
const PSYCHUBE_CATEGORY_KEY = '\u5fc3\u76f8'
const STORY_CATEGORY_KEY = '\u5267\u60c5'
const RANDOM_CHARACTER_STANDEE_SRC =
  CRAWLER_CHARACTER_COVER_SRC[Math.floor(Math.random() * CRAWLER_CHARACTER_COVER_SRC.length)] ?? GLOBAL_BACKGROUND_IMAGE_SRC
const RANDOM_PSYCHUBE_COVER_SRC =
  CRAWLER_PSYCHUBE_COVER_SRC[Math.floor(Math.random() * CRAWLER_PSYCHUBE_COVER_SRC.length)] ?? GLOBAL_BACKGROUND_IMAGE_SRC
const RANDOM_STORY_COVER_SRC =
  CRAWLER_STORY_COVER_SRC[Math.floor(Math.random() * CRAWLER_STORY_COVER_SRC.length)] ?? GLOBAL_BACKGROUND_IMAGE_SRC

export function getCategoryCoverSrc(key: string): string {
  if (key === CHARACTER_CATEGORY_KEY) return RANDOM_CHARACTER_STANDEE_SRC
  if (key === PSYCHUBE_CATEGORY_KEY) return RANDOM_PSYCHUBE_COVER_SRC
  if (key === STORY_CATEGORY_KEY) return RANDOM_STORY_COVER_SRC
  return GLOBAL_BACKGROUND_IMAGE_SRC
}
