import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** 复刻自 Stitch 设计稿的 Tailwind 配置（由原 index.html 内联配置平移而来，构建期生效） */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // —— 四个设计稿共享的固定令牌（palette A / advanced）——
        'on-primary': '#561f00',
        'on-primary-container': '#4b1b00',
        'surface': '#1c110b',
        'on-primary-fixed': '#351000',
        'error': '#ffb4ab',
        'primary-container': '#ed6916',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#7a3000',
        'surface-tint': '#ffb693',
        'inverse-primary': '#a04100',
        'surface-dim': '#1c110b',
        'primary-fixed-dim': '#ffb693',
        'surface-variant': '#40322b',
        'surface-container-low': '#251913',
        'on-surface-variant': '#e0c0b2',
        'outline': '#a78b7e',
        'on-error': '#690005',
        'surface-container-highest': '#40322b',
        'outline-variant': '#584237',
        'background': '#1c110b',
        'primary-fixed': '#ffdbcc',
        // —— 页面间存在差异的令牌（CSS 变量化，默认 palette A）——
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface, 60 45 39) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface, 246 222 212) / <alpha-value>)',
        'on-background': 'rgb(var(--c-on-background, 246 222 212) / <alpha-value>)',
        'on-secondary': 'rgb(var(--c-on-secondary, 39 51 51) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--c-on-secondary-container, 174 187 187) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed, 18 30 30) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant, 61 73 73) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface, 246 222 212) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--c-on-tertiary, 54 47 37) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--c-on-tertiary-container, 48 41 31) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed, 33 27 17) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant, 78 70 59) / <alpha-value>)',
        'primary': 'rgb(var(--c-primary, 226 97 11) / <alpha-value>)',
        'secondary': 'rgb(var(--c-secondary, 188 201 201) / <alpha-value>)',
        'secondary-container': 'rgb(var(--c-secondary-container, 63 75 75) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--c-secondary-fixed, 216 229 229) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim, 188 201 201) / <alpha-value>)',
        'surface-bright': 'rgb(var(--c-surface-bright, 69 54 47) / <alpha-value>)',
        'surface-container': 'rgb(var(--c-surface-container, 42 29 23) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high, 53 39 33) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest, 22 12 7) / <alpha-value>)',
        'tertiary': 'rgb(var(--c-tertiary, 209 197 182) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--c-tertiary-container, 154 143 130) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--c-tertiary-fixed, 238 224 209) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim, 209 197 182) / <alpha-value>)',
      },
      fontFamily: {
        'data-mono': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
        'body-lg': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
        'body-md': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
        'headline-sm': ['"Libre Caslon Text"', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'serif'],
        'headline-lg': ['"Libre Caslon Text"', 'serif'],
        'display-lg': ['"Libre Caslon Text"', 'serif'],
        'label-caps': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
        'data-label': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
        'data-code': ['"JetBrains Mono Variable"', '"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'data-code': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'panel-padding': '20px',
        'margin-desktop': '48px',
        'gutter': '24px',
        'unit': '4px',
        'block-gap': '24px',
      },
      boxShadow: {
        'hard': '8px 8px 0px 0px rgba(0,0,0,0.8)',
        'glow': '0 0 15px rgba(226, 97, 11, 0.4)',
      },
    },
  },
  plugins: [forms, containerQueries],
}
